@base_url=http://localhost:3333
@ong_id=17d2a11ceb67592a

### Create
POST {{base_url}}/incidents HTTP/1.1
Content-Type: application/json
Authorization: {{ong_id}}

{
  "title": "caso 1",
  "description": "Detalhes do caso",
  "value": 120
}

### List
GET {{base_url}}/incidents HTTP/1.1
Content-Type: application/json

### Delete
DELETE {{base_url}}/incidents/1 HTTP/1.1
Content-Type: application/json
Authorization: {{ong_id}}
